apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: {{ include "myapp.name" . }}
    env: {{ .Values.environment }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 3000
  type: {{ .Values.service.type }}
